### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [shamazmazum/neural-classifier#1]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id c1cf19290d87901aca1e8a90a46ec8c8d58d9b42

*neural-classifier* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: Error finding package for symbol "*KNOWN-BACKENDS*":

```

*neural-classifier/mnist* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: Error finding package for symbol "*KNOWN-BACKENDS*":

```

*neural-classifier/tests* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: Error finding package for symbol "*KNOWN-BACKENDS*":

```

[Full log here](http://report.quicklisp.org/2021-03-29/failure-report/neural-classifier.html)

**Comment by shamazmazum** [comment]
Hi! This is probably due to recent incompatible update of `rigetti/magicl `. You may have to update it in the first place.

**Comment by quicklisp** [comment]
I'm already using the latest release of magicl and I still get this error.

**Comment by shamazmazum** [comment]
I see. But the error is during compilation of magicl, not neural-classifier. Can you compiler magicl separately?
Missing `magicl.backends` package is in `src/packages.lisp` which belongs to `magicl/core` system. Maybe some fasl cache needs to be cleaned?

**Comment by shamazmazum** [comment]
I think I can close this now :)
